# startIndex는 실제 데이터 탐색 시작 row 값으로, 6행부터 찾아야 하면 5라고 입력하면 됨.
# 노선 필터
[target]
"sj" = ["강남B", "강동B", "강동A", "평택A", "평택B", "분당A", "하남"]
"이그린" = ["시흥", "수지", "안성", "단원", "수정", "화성B",]

#청구업체 필터
[company]
"sj" = ["SJ"]
"이그린" = ["이그린","이그린간선","SJ(이그린)","SJ간선(이그린)"]

[j2]
no = "No."
date = "날 짜"
licensePlate = "차량 번호"
route = "운행 노선"
# source = "상차지"
# destination = "하차지"
reference = "비 고"
targetCompany = "간선사"
company = "소 속"
postpaid = "후 불"
j2Postpaid = "J2 후 불"
totalFee = "청 구"
startIndex = 5

[cj]
no = "NO"
date = "출발일자"
licensePlate = "차량번호"
trailerPlate = "샤시번호"
source = "출발터미널"
destination = "도착터미널"
layoverNum = "경유회수"
carType = "차량구분"
reference = "비고"
detourFeeType = "차량톤수"
detourFee = "추가운임"
detourFeeType3 = "추가운임구분3"
detourFee3 = "추가운임3"
detourFair = "경유비"
multiTourPercent = "다회전기준요율"
totalFee = "총운송비용"
startIndex = 1

[gansun]
no = "NO"
date = "출발일자"
licensePlate = "차량번호"
trailerPlate = "샤시번호"
source = "출발터미널"
destination = "도착터미널"
layoverNum = "경유회수"
carType = "차량구분"
reference = "비고"
detourFeeType = "차량톤수"
detourFee = "추가운임"
detourFeeType3 = "추가운임구분3"
detourFee3 = "추가운임3"
detourFair = "경유비"
multiTourPercent = "다회전기준요율"
totalFee = "총운송비용"
startIndex = 1

[direct]
# 수지
"죽전이엔알" = "수지"
"바이앤바이" = "수지"
"뉴스킨덕평" = "수지"
"뉴스킨음성" = "수지"
"유빈창고" = "수지"
"아모레김천" = "수지"
"아모레오산" = "수지"
"메가" = "수지"
"인화락" = "수지"
"허벌" = "수지"
"송학" = "수지"
"공감" = "수지"
"메나" = "수지"
"초초스" = "수지"
"다나인턴" = "수지"
"제이엠" = "수지"
"소리바다" = "수지"
"다솜식품" = "수지"
"동인" = "수지"
"엠코2창고" = "수지"
"휴럼" = "수지"
"HAM" = "수지"
"엠코" = "수지"
"제이코" = "수지"
"이앤알" = "수지"
"씨에스에이" = "수지"
"유빈" = "수지"
"엠코2" = "수지"
"죽전이앤알" = "수지"
"이엔알" = "수지"
"동백냉동" = "수지"
"마음이가" = "수지"
"그리티" = "수지"
"청덕창고" = "수지"
"매나" = "수지"
"동백냉장" = "수지"
# 안성
"중원" = "안성"
"지앤지" = "안성"
"피앤에이패키지" = "안성"
"하얀티슈" = "안성"
"동아방송" = "안성"
"녹돈영농조합" = "안성"
"녹돈" = "안성"
"녹돈영농" = "안성"
"쿠팡안성4FC센터" = "쿠팡안성"
"다복" = "안성"
"우람물류" = "안성"
"토니모리" = "안성"
# 시흥
"태은" = "시흥"
"포동" = "시흥"
"하늘" = "시흥"
"이앤비" = "시흥"
"홈앤하우스" = "시흥"
"현대통합물류" = "시흥"
"시흥1" = "시흥"
"디딤테크" = "시흥"
#단원
"유니토아" = "단원"
"찬솔나라" = "단원"
#강남B
"강남B1" = "강남B"
#강동B
"명일" = "강동B"
"명일우진" = "강동B"
#강동A

#수정
"골드플레이트" = "수정"
"골든플레이트" = "수정"
"골드" = "수정"
"허브로지스" = "수정"
"초록마을" = "수정"
"동현물류" = "수정"
"지엠아이유통" = "수정"
"에코홀딩스" = "수정"
"에코" = "수정"
"동현물류/골드플레이트" = "수정"
"무아스" = "수정"
"동현/골드플레이트" = "수정"
"마켓컬리" = "수정"
"무아스/골드플레이트" = "수정"
"동현" = "수정"
"우성바이오텍" = "수정"
"우성바이오택" = "수정"
"아세아도" = "수정"
#평택A
"네스프레소" = "평택A"
"네소프레소" = "평택A"
"에스디에스" = "평택A"
"케이와이" = "평택A"
#평택B
"평택BMP" = "평택B"
#화성B
"위드" = "화성B"
"네이처" = "화성B"
"네이쳐" = "화성B"
"신봉담" = "화성B"
"스마트" = "화성B"
"비비안" = "화성B"
"위닉스" = "화성B"
"에스엘" = "화성B"
"에스앨" = "화성B"
"애스엘" = "화성B"
"애스앨" = "화성B"
"건일바이오" = "화성B"
"에이치디유통" = "화성B"
"자몽나라" = "화성B"
"엑소" = "화성B"
"동우엘앤씨" = "화성B"
"동우엘엔씨" = "화성B"
"동우앨엔씨" = "화성B"
"동우앨앤씨" = "화성B"
"레위" = "화성B"
"래위" = "화성B"
#강동B
#하남
#곤지암