# startIndex는 실제 데이터 탐색 시작 row 값으로, 6행부터 찾아야 하면 5라고 입력하면 됨.
# 노선 필터
[target]
"mp" = ["이천MP", "이천"]
"sj" = ["원삼", "강남B", "강동B", "강동A", "수정", "평택A", "평택B", "분당A", "하남"]
"이그린" = ["시흥", "수지", "안성", "단원", "곤지암", "군포"]

#청구업체 필터
[company]
"mp"=["이천MP"]
"sj" = ["SJ"]
"이그린" = ["수지지점", "안성지점", "이그린", "시흥지점"]

[j2]
no = "No."
date = "날 짜"
licensePlate = "차량 번호"
route = "운행 노선"
reference = "비 고"
targetCompany = "청구 업체"
startIndex = 5

[cj]
no = "NO"
date = "출발일자"
licensePlate = "차량번호"
source = "출발터미널"
destination = "도착터미널"
layoverNum = "경유회수"
carType = "차량구분"
reference = "비고"
startIndex = 1

[gansun]
no = "NO"
date = "출발일자"
licensePlate = "차량번호"
source = "출발터미널"
destination = "도착터미널"
layoverNum = "경유회수"
carType = "차량구분"
reference = "비고"
startIndex = 1

[direct]
# 수지
"죽전이엔알" = "수지"
"바이앤바이" = "수지"
"뉴스킨덕평" = "수지"
"뉴스킨음성" = "수지"
"유빈창고" = "수지"
"아모레김천" = "수지"
"아모레오산" = "수지"
"메가" = "수지"
"인화락" = "수지"
"허벌" = "수지"
"송학" = "수지"
"공감" = "수지"
"메나" = "수지"
"초초스" = "수지"
"다나인턴" = "수지"
"제이엠" = "수지"
"소리바다" = "수지"
"다솜식품" = "수지"
"동인" = "수지"
"엠코2창고" = "수지"
"휴럼" = "수지"
"HAM" = "수지"
"엠코" = "수지"
"제이코" = "수지"
"동백냉장" = "수지"
"이앤알" = "수지"
"씨에스에이" = "수지"
"유빈" = "수지"
"엠코2" = "수지"
# 안성
"중원" = "안성"
"지앤지" = "안성"
"피앤에이패키지" = "안성"
"하얀티슈" = "안성"
"동아방송" = "안성"
"녹돈영농조합" = "안성"
"녹돈" = "안성"
"녹돈영농" = "안성"
# 시흥
"태은" = "시흥"
"포동" = "시흥"
"하늘" = "시흥"
#단원
"유니토아" = "단원"
"찬솔나라" = "단원"
#시흥
"시흥1" = "시흥"
#강남B
"강남B1" = "강남B"
#강동B
"명일" = "강동B"
"명일우진" = "강동B"
#강동A
"송파B" = "강동A"
#수정
"골드플레이트" = "수정"
"골든플레이트" = "수정"
"골드" = "수정"
"허브로지스" = "수정"
"초록마을" = "수정"
"동현물류" = "수정"
"지엠아이유통" = "수정"
"에코홀딩스" = "수정"
"에코" = "수정"
#평택A
"네스프레소" = "평택A"
"네소프레소" = "평택A"
"에스디에스" = "평택A"
#평택B
"평택BMP" = "평택B"