# startIndex는 실제 데이터 탐색 시작 row 값으로, 6행부터 찾아야 하면 5라고 입력하면 됨.
# 노선 필터
[target]
"sj" = ["이천MP", "이천"]
"이그린" = ["시흥", "수지", "안성", "단원"]

#청구업체 필터
[company]
"sj" = ["이천MP"]
"이그린" = ["수지지점", "안성지점", "이그린", "시흥지점"]

[j2]
no = "No."
date = "날 짜"
licensePlate = "차량 번호"
route = "운행 노선"
reference = "비 고"
targetCompany = "청구 업체"
startIndex = 5

[cj]
no = "NO"
date = "출발일자"
licensePlate = "차량번호"
source = "출발터미널"
destination = "도착터미널"
layoverNum = "경유회수"
carType = "차량구분"
reference = "비고"
startIndex = 1

[gansun]
no = "NO"
date = "출발일자"
licensePlate = "차량번호"
source = "출발터미널"
destination = "도착터미널"
layoverNum = "경유회수"
carType = "차량구분"
reference = "비고"
startIndex = 1

[direct]
# 수지
"죽전이엔알" = "수지"
"바이앤바이" = "수지"
"뉴스킨덕평" = "수지"
"뉴스킨음성" = "수지"
"유빈창고" = "수지"
"아모레김천" = "수지"
"아모레오산" = "수지"
"메가" = "수지"
"인화락" = "수지"
"허벌" = "수지"
"송학" = "수지"
"공감" = "수지"
"메나" = "수지"
"초초스" = "수지"
"다나인턴" = "수지"
"제이엠" = "수지"
"소리바다" = "수지"
"다솜식품" = "수지"
"동인" = "수지"
"엠코2창고" = "수지"
"휴럼" = "수지"
"HAM" = "수지"
"엠코" = "수지"
"제이코" = "수지"
# 안성
"중원" = "안성"
"지앤지" = "안성"
"피앤에이패키지" = "안성"
"하얀티슈" = "안성"
"동아방송" = "안성"
"녹돈영농조합" = "안성"
# 시흥
"태은" = "시흥"
"하늘" = "시흥"
"찬솔나라" = "시흥"
#단원
"유니토아" = "단원"
#시흥
"시흥1" = "시흥"