# startIndex는 실제 데이터 탐색 시작 row 값으로, 6행부터 찾아야 하면 5라고 입력하면 됨.
[j2]
no = "no"
date = "날 짜"
licensePlate = "차량 번호"
route = "운행 노선"
startIndex = 5

[cj]
no = "NO"
date = "출발일자"
licensePlate = "차량번호"
source = "출발터미널"
destination = "도착터미널"
startIndex = 1