# 간선
# "출발지" = [[도착지], [청구업체]]
[route]
"처인"= [ ["곤지암", "옥천", "대전"], ["SJ간선"]]
"화성A" = [ ["대전"], ["SJ간선"] ]
"경기광주" = [ ["대전", "곤지암"], ["SJ간선"] ]
"평택A" = [ ["옥천"], ["SJ간선"] ]
"평택B" = [ ["옥천"], ["SJ간선"] ]
"분당A" = [ ["대전", "곤지암"], ["SJ간선"] ]
"강남B" = [ ["곤지암"], ["SJ간선"] ]
"강북" = [ ["옥천"], ["SJ간선"] ]
"권선" = [ ["대전", "곤지암"], ["SJ간선"] ]
"화성B" = [ ["곤지암"], ["SJ간선"] ]
"단원" = [ ["옥천"], ["SJ간선"] ]
